# Generated by Django 3.0.1 on 2020-04-22 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('industry_name', models.CharField(max_length=64)),
                ('refine_road_address', models.CharField(max_length=256)),
                ('refine_num_address', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=32)),
                ('zip_code', models.CharField(max_length=16)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('last_updated_at', models.DateField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='odso.City')),
            ],
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['latitude', 'longitude'], name='odso_store_latitud_340bb9_idx'),
        ),
    ]
